### ISSUE TITLE
Brushing and linking data structures are not updated properly on filtering

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#101]
Setting filters (confidence has filters by default) and then brushing a religion will sometimes link places where those religions do not exist *under the applied filters.* Specifically, it seems the data structures for storing the relationships between the data attributes are not properly updated on filtering, but should be.

Example (production server data): Default confidence filters apply, also some religion filters, which however do not matter in this case. Brushing SYR links Samarqand (which has SYR *without* filters, but not under the current filters): 
<img width="869" alt="Test linking Screenshot 2022-03-05 130413" src="https://user-images.githubusercontent.com/9373678/157617577-fb79efd0-3593-4ad7-8262-271121d439e9.png">

Visualization state:
``` json
{"show-filtered":true,"display-mode":"religion","timeline-mode":"qualitative","map-mode":"clustered","confidence-aspect":"religion_confidence","map-state":{"zoom":6,"center":{"lat":38.013476231041935,"lng":67.50000000000001},"base_layer":"light","overlay_layers":["markerLayer"]},"filters":{"religion":{"type":"simple","filter":[5,4]},"time":null,"sources":null,"confidence":{"time_confidence":["certain","probable","contested","uncertain","false",null],"location_confidence":["certain","probable","contested","uncertain","false",null],"place_attribution_confidence":["certain","probable","contested","uncertain","false",null],"source_confidences":["certain","probable","contested","uncertain","false",null],"interpretation_confidence":["certain","probable","contested","uncertain","false",null],"religion_confidence":["certain","probable","contested","uncertain","false",null]},"tags":true,"location":null,"places":null},"metadata":{"version":"v1.0.5","createdBy":"max","createdAt":"2022-03-10T08:30:08.588Z","source":"filesystem","evidenceCount":4564}}
```

**Comment by tutebatti** [comment]
> will sometimes

I assume we have no idea how often this is the case? This would matter in deciding if this is urgent or not.

**Comment by mfranke93** [comment]
>  I assume we have no idea how often this is the case? This would matter in deciding if this is urgent or not.

I suspect this happens most of the time, but is only noticeable in some specific cases where the number of evidences per city/glyph is small enough, such as the case above.

Nevertheless, I have time to take a look at it now, so it should hopefully be fixed in time for the public release.
