### ISSUE TITLE
sorting of sources in "source view"

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#103]
In the list of sources in the _source view_, sources with the same number of evidences (especially with 0 evidences) should be sorted alphabetically according to the `short name`, e.g. "AtKG".

**Comment by mfranke93** [comment]
![image](https://user-images.githubusercontent.com/9373678/157855616-71b2dafd-d650-4aef-bfde-d3d98ad79327.png)
