### ISSUE TITLE
add button in "source view" to change sorting

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#104]
In the _source view,_ two buttons should be added to switch between alphabetical order (using the `short name`) and the only currently available ordering, i.e. according to number of evidences.

(Cf. also #103.)

**Comment by tutebatti** [comment]
Update: possibly, this will not be needed.

**Comment by tutebatti** [comment]
I had another look at this in the current public (but not yet public) instance. With 33 sources, another button to sort by alphabetical order would be nice.

**Comment by mfranke93** [comment]
> In the source view, two buttons should be added to switch between alphabetical order (using the short name) and the only currently available ordering, i.e. according to number of evidences.

Just to clarify, should it be possible to reverse-sort as well? Most interactive tables (e.g., Excel) offer this. So, clicking a table header once sorts by that column, clicking again sorts by that column in descending order.

Offering just two orders (ascending by alphabetical source short name, descending by number of evidences) would be easier to implement, but does that cover all your use cases?

**Comment by tutebatti** [comment]
I would say reverse is not necessary (33 is not *that* many after all).

**Comment by mfranke93** [comment]
Would a control like this (in the header of the view) work?

![image](https://user-images.githubusercontent.com/9373678/162009084-ee6b636c-eff6-400f-b410-8cabf9632677.png)

**Comment by tutebatti** [comment]
Yes, absolutely. I would position it a little bit more to the right, to keep it separate from the other three buttons.

**Comment by mfranke93** [comment]
Okay, this should be finished now.

@tutebatti : Maybe consider sending the info text additions (fcd3e5273005dcaaf1a2439c8ae17d718e047420) to the native speaker as well. Or at least take a brief look. I tried to consider the terminology changes we discussed elsewhere, but I am not sure if the descriptions are understandable enough.
