### ISSUE TITLE
appearance of mouse cursor in time line

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#107]
In Dorothea's Firefox, when filtering via the _time line,_ instead of a grabbing hand
![grafik](https://user-images.githubusercontent.com/7239968/158569389-4c77da7c-8a0c-4234-aa63-13aa13af367f.png)
something like this
![grafik](https://user-images.githubusercontent.com/7239968/158569470-16e658ba-263d-46c8-b9dd-c8744de2b402.png)
is shown.

We could simply change the info text, adding something like "(or a four-headed arrow)". Any thoughts, @mfranke93?

PS: I would like something like this: 
![grafik](https://user-images.githubusercontent.com/7239968/158569557-371f9b52-74b2-4955-a7c8-1c3a0ae6a46e.png)
;D

**Comment by mfranke93** [comment]
I assume she is on Windows? See [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=275174): The "grabbing hand" (`move`) cursor is the one that *should* be shown, but on Windows Firefox, the `all-scroll` cursor is shown instead.

I would highly discourage changing anything about the cursors themselves. Although possible, it might make the icons used less familiar for most visitors. I don't think many visitors will use the combination of Firefox + Windows (FF has a market share of under 8% on desktop according to Wikipedia, not all of these will be on Windows), but if you feel it is necessary you can change the text accordingly.

**Comment by tutebatti** [comment]
So this bug is 18 years old? :D Anyway, thanks for clarification. I will suggest an addition in the info text in parentheses.
