### ISSUE TITLE
"SET MINUS" or "SET SUBSTRACTION" in place filtering

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#108]
The tooltip on mouse hover and the info text on the location differ as to this
![grafik](https://user-images.githubusercontent.com/7239968/158570694-78f0557e-9abb-46eb-97d9-6d3252c1d65f.png)
being SET MINUS (visualization) or SET SUBSTRACTION (info text).

Please decide which is better, implement in visualization (if needed), while I would adapt the info text (if needed).

**Comment by mfranke93** [comment]
There are a few different ways to call this, and most of them are quite mathematical, because all of this comes from set theory. But I would suggest to use the "SET SUBTRACTION" (not "substraction") variant.

**Comment by tutebatti** [comment]
Thank you. So would you change the tooltip in the visualization from "MINUS" to "SUBTRACTION"?
