### ISSUE TITLE
Explanations of visualization types

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#111]
At the moment, there are only the following headings in the section on visualization types in the visualization documentation:

- Bar Chart and Stacked Bar Chart
- Stacked Area Chart
- Indented Tree
- Gantt Chart

If there's no time to add text, I would suggest to simply delete that. Alternatively, there could be simple sentence such as "The following types of visualizations are used in Damast:" followed by an unordered list and links to an external online reference.

**Comment by mfranke93** [comment]
I do not think this is a big issue, I can add some text and maybe an image to this before the deadline. Thanks for creating an issue, I implicitly had this as part of #46, but closed that issue before all the non-infobox texts were added.

**Comment by mfranke93** [comment]
@tutebatti I finished the explanation of the visualizations. I kept it short and basic, and linked to the relevant sections further down in the info texts for (visual) examples.

**Comment by mfranke93** [comment]
Since this is also on the `feature/rephrase-info` branch and will eventually be merged from there, I would close this issue now. Feel free to re-open it if you see any more need to discuss or change anything.
