### ISSUE TITLE
Changes on the automatically generated settlement page

### ISSUE THREAD

**Issue by rpbarczok** [UniStuttgart-VISUS/damast#113]
I suggest the following changes in the content of the place URL:
1.	Paragraph “See Also”:
At the moment it looks like this:
-	[DARE:22329 in Digital Atlas of the Roman Empire (DARE)](http://imperium.ahlfeldt.se/places/22329).
I would rather have:
-	at Digital Atlas of the Roman Empire (DARE): http://imperium.ahlfeldt.se/places/22329

2.	Sources
At the moment it looks like this:
Fiey, Jean Maurice. Pour un Oriens Christianus novus: Répertoire des diocèses Syriaques orientaux et occidentaux. Beiruter Texte und Studien 49. Stuttgart: Steiner, 1993. (Literature): p. 115.
	I would rather have
Fiey, Jean Maurice. Pour un Oriens Christianus novus: Répertoire des diocèses Syriaques orientaux et occidentaux. Beiruter Texte und Studien 49. Stuttgart: Steiner, 1993. 115. (Literature)

I.e. move the source type at the end of the whole statement and remove the “p.”

**Comment by tutebatti** [comment]
Sounds good.

**Comment by tutebatti** [comment]
We can take care of this a little later, as the place URI pages will be dynamically updated.
