### ISSUE TITLE
"<xyz> confidence" in texts

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#116]
After the first revision by the native speaker, it seems as if a term such as "religion confidence" is extremely awkward. To clarify: We do not need to change this anywhere in the code, but there are quite a few (i.e. to many, not to care, and only a few, so we can easily change that, I believe) instances in the different texts (such as reports, info texts, etc.), where we could easily verbalize that differently.

I have used `grep -nR "<xyz> confidence" *` with `<xyz>` being either

- source
- interpretation
- location
- religion
- place attribution

and wrote the output to one file each to get an overview. Sometimes, it's just 4 or 5 lines of code, sometimes it's more.

@mfranke93 Did I get most or all instances of the terms with that? 

I will need to make sure that the suggested term "confidence *of* interpretation" can be applied to the other aspects to. (To me, "confidence *of* religion" doesn't sound right either.) Once I established that list, I assume we could relatively easily change this, right?

**Comment by mfranke93** [comment]
> @mfranke93 Did I get most or all instances of the terms with that?

Hard to tell without seeing the list. I would say that, if you add case insensitivity to your `grep` call, it should be all:

``` bash
grep -inr "<xyz> confidence" damast/ docs/ src/
```

But there might be places where there is a line break between "<xyz>" and "confidence", but probably not in the HTML, TeX, and TypeScript files (there are strings in those that appear in the finished HTML in the visualization).

We have already used the terms, as they are now, in publications, so they are "out there." You decide how problematic that is.

**Comment by mfranke93** [comment]
> Concerning the terms used in previous publications: which one are you referring to specifically? In your field? The native speaker (and another one I also talked with) were pretty clear about the term being problematic. Even more so concerning https://github.com/UniStuttgart-VISUS/damast/issues/117.

M. Franke, R. Barczok, S. Koch, and D. Weltecke. Confidence as first-class attribute in digital humanities data. Proc. VIS4DH Workshop, Oct 2019. ([PDF](http://vis4dh.dbvis.de/papers/2019/VIS4DH2019_paper_1.pdf))

**Comment by tutebatti** [comment]
Ok, thanks. Should I open a new branch for the changes outside the info texts? Or how do we go about this?

**Comment by mfranke93** [comment]
> Should I open a new branch

Given how long-running the `feature/rephrase-info` branch has become, I would say that is a good idea.

>  for the changes outside the info texts?

 I would say branch from `feature/rephrase-info`, but implement all changes there, even those not in the info texts. And then open a PR back onto the `feature/rephrase-info` branch when finished. I merged the release `v1.1.0` from `main` into that branch on Friday, so it should be pretty up to date.

I would also suggest doing #117 in the same branch. Both are just phrasing changes.

**Comment by tutebatti** [comment]
> I would also suggest doing #117 in the same branch.

I.e. in the same subbranch of `feature/rephrase-info`, correct?

**Comment by tutebatti** [comment]
I have made several commits in a separate branch regarding this issue. As soon as the native speaker has gone through the text, I might adapt my changes once more together with implementing the other corrections.

I have left out everything connected to the annotator and the geodb-editor.
