### ISSUE TITLE
"an evidence"/"evidences" in text

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#117]
Similar to issue #116, the native speaker has strongly recommended not to use the word "evidence" as countable; rather, it needs a counter such as "piece/s of evidence." So I first need to apologize to @rpbarczok regarding what was discussed in #112.

Next, I point out again: We do not need to change the code as such, but only the texts. Here, too, I checked for occurrences using `grep -nR "evidences" *` as well as `grep -nR "an evidence" *`. Of the 169 occurrences with the plural, about half are part of the texts that are being revised anyway. Some are in the pieces of text used for generating reports and such. The 25 occurrences of the singular are almost exclusively confined to the info texts.

When changing this, we should distinguish the collective "evidence" (e.g. as a heading in the report), and the countable "piece/s of evidence" for the singular and plural, respectively. As in the case of #116, I hope this revision is feasible and I apologize again for the confusion I caused.

**Comment by mfranke93** [comment]
As with #116, I would advise you to add case-insensitivity when searching for occurences. Other than that, I have no objections.

**Comment by tutebatti** [comment]
I have made a commit (2415a2071717c32417a1f689cf330bfb0b3ed616) on a separate branch regarding this issue. As soon as the native speaker has gone through the text, I might adapt my changes once more together with implementing the other corrections.

I have left out everything connected to the annotator and the geodb-editor.

**Comment by mfranke93** [comment]
> we should distinguish the collective "evidence" (e.g. as a heading in the report)

If I see correctly, you still changed the report headings to "Pieces of Evidence". Was that your intention?

**Comment by tutebatti** [comment]
> If I see correctly, you still changed the report headings to "Pieces of Evidence". Was that your intention?

I still try to figure out, if the collective ("Gebirge") or the countable plural ("Berge") is more suitable in that case. Here, too, we'd best ask a native speaker.
