### ISSUE TITLE
bars not aligned properly in Chromium

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#126]
![image](https://user-images.githubusercontent.com/7239968/161969065-5dd382fb-96d4-48ee-94e5-e6fcbaab97e5.png)

This might not be an issue in more common browsers, but in Chromium (Version 100.0.4896.60 (Offizieller Build) for Linux Mint (64-Bit)) the bars in the _source view_ are not aligned properly.

The same is true about the bars in the _tag view._

**Comment by mfranke93** [comment]
Yes. The visualization was designed and intended for use with Firefox. I will not do a "perfect" fix here, but provide a fallback for browsers that do not support `subgrid` ([all but Firefox at the moment](https://caniuse.com/mdn-css_properties_grid-template-rows_subgrid)). Ideally, in the near future other browsers will catch up here.

**Comment by tutebatti** [comment]
I might have missed that, but we should probably add the information "use with Firefox for best results" to the startpage.

**Comment by mfranke93** [comment]
That might be good. I mean, the Chrome experience should not be as bad as your screenshot, but I don't think we can serve everyone. "For best results" seems like a good compromise.
