### ISSUE TITLE
Help integrating custom mapbox map into map-styles.json

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#136]
I managed to import your custom style into the mapbox account of Damast no problem. I also created two other ones. For integrating them into the visualization, i.e. including them in the `map-styles.json`, I had a look at the file src/common/map-styles.ts to check how this is done.

1) I used the URL from that file as a blueprint, replacing the username and the id of the map:

`https://api.mapbox.com/styles/v1/damast/cl14rtpdk001115o1jrn73m7y/tiles/256/{z}/{x}/{y}?access_token={accessToken}`

2) I set `is_mapbox` to `true`.

3) I used the key `accessToken` with the respective value from the mapbox sharing menu.

When restarting with `sudo systemctl restart damast` I get no error, but the visualization loads only the fallback maps (osm + dare).

Any ideas? Maybe some settings of the map in mapbox or in the mapbox account?

**Comment by mfranke93** [comment]
As usual, the error log is helpful :wink: :

```
[2022-05-04T09:29:37 +0200] [ERROR] [-] [vis.map-styles] Something went wrong when loading the map style file, using default selection: Expecting value: line 9 column 24 (char 288)
```

Looking into the `map-styles.json.new` (I assume that was the one you tried), indeed there is an error in line 9, column 24. The vim version on the server even helpfully highlights this as a syntax error: Single quotation marks are not valid in JSON.

Looking into the Python or TypeScript sources for the *structure* of the map style file is fine, but the *syntax* needs to be adapted to JSON.

**Comment by tutebatti** [comment]
The log... of course. :see_no_evil: ... and those unforgiving JSON files... thank you! :smile:

**Comment by mfranke93** [comment]
Slight note: It probably won't break anything, but right now, the file has two default maps (`mapbox` and `osm`). Maybe remove one ``"default_": true`.
