### ISSUE TITLE
Problems with cookie dialogue in Firefox?

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#137]
Yesterday, someone from our team in Berlin tried visiting the public instance at damast.geschichte.hu-berlin.de with Firefox (on Windows) and the "Accept" button in the cookie dialogue did not respond. On my PC, with Firefox (on Linux) I got a grayed-out start page but not dialogue at all. 

Happy about any recommendations to track these bugs.

**Comment by tutebatti** [comment]
Update: Changing my cookie preferences in the browser solved the problem on my PC, it seems. I will ask the person in Berlin to double-check, too.

**Comment by mfranke93** [comment]
Did they go directly to the visualization? Because I noticed something weird as well yesterday, with the cookie dialog over the visualization not reacting to clicks. This has not happened before because you have to have cookies accepted to even log in.

> Happy about any recommendations to track these bugs.

Screenshots and browser versions!

**Comment by tutebatti** [comment]
> Did they go directly to the visualization?

No. I did neither.

Will check about the screenshots and browser versions.

**Comment by tutebatti** [comment]
I got this reply:

> konnte den Fehler an meinem Surface Go reproduzieren:
>
> Wenn ich beim Aufrufen der Startseite "No cookies" auswähle, kann ich diese Einstellung normal bestätigen und der Dialog  verschwindet. Aber wenn ich dann die Visualisierung ansteuere, öffnet sich erneut der Dialog und lässt sich nicht schließen, egal welche Option ich auswähle.
>
> Der gleiche Fehler tritt auch in Chrome und Edge auf.

I also got another user with the same problem on Firefox (on Windows), waiting for details.

**Comment by mfranke93** [comment]
> "No cookies"

Okay, yeah... Maybe this should be added as information in the popup. "No cookies" means **no cookies;** i.e., not even a small cookie that saves the information that no cookies are desired. So, the cookie dialog will reappear on each new page. That part is non-negotiable for GDPR compliance, I'm afraid. The "no cookies" option is not recommended for anyone who actually wants to use the site (even though it could work without login).

The other part (not clickable in the vis) is a bug. I've opened an issue and will look into that (#139 ).

**Comment by tutebatti** [comment]
So the problem encountered is a combination of a "bad" user choice and the bug, correct?

**Comment by mfranke93** [comment]
That is correct. I will try to add some more explanation to the "No cookies" option without making it too lengthy. The current descriptions are very much geared towards the version at VIS with login.

**Comment by mfranke93** [comment]
> On my PC, with Firefox (on Linux) I got a grayed-out start page but not dialogue at all.

I'm still curious what happened here. Can you clear cookie preferences (either via settings, or via debugger (F12) > Storage > Cookies > [select page] > Rightclick -> Delete all) and try to reproduce that?

**Comment by tutebatti** [comment]
> That is correct. I will try to add some more explanation to the "No cookies" option without making it too lengthy.

I would also "nudge" users by having the second option (essential cookies) as the default and put it at the top.

**Comment by tutebatti** [comment]
> Can you clear cookie preferences (either via settings, or via debugger (F12) > Storage > Cookies > [select page] > Rightclick -> Delete all) and try to reproduce that?

I have Firefox 99.0.1 on Linux Mint (mint-001 - 1.0):

![grafik](https://user-images.githubusercontent.com/7239968/166894983-00889d3a-0ca0-4109-a655-0ecfd3faf894.png)

I was just able to reproduce the bug by closing and re-opening Firefox. (Cookies are deleted when closing.)

![grafik](https://user-images.githubusercontent.com/7239968/166895035-71be9141-eb68-422c-853b-81146eb7151e.png)


The cookie-dialogue is visible for a very short moment when going back and forth between the start page and the visualization using the browser navigation.

**Comment by tutebatti** [comment]
I can add that going to https://damast.geschichte.hu-berlin.de/cookie-preferences I get nothing:

![grafik](https://user-images.githubusercontent.com/7239968/166895711-b0732c60-3df5-4401-84d3-052dae2c14b0.png)

Note that this page is not grayed-out!

**Comment by mfranke93** [comment]
Weird. Can you put a screenshot of the F12 console and the inspector window (where the DOM is shown)?

> Note that this page is not grayed-out!

Yeah, that should be like that, because the content is on the page itself.

**Comment by mfranke93** [comment]
And do you have any popup blocker plugins installed? If so, does it happen even if you deactivate them? I'm on FF99 on Linux as well and do not have these issues.

**Comment by tutebatti** [comment]
> Can you put a screenshot of the F12 console and the inspector window (where the DOM is shown)?

![grafik](https://user-images.githubusercontent.com/7239968/166896369-fa5e1718-afbe-4230-8d66-46e951a524f8.png)

![grafik](https://user-images.githubusercontent.com/7239968/166896523-bc0ab04d-dba5-4a64-ae55-b6472dda8bd2.png)

**Comment by tutebatti** [comment]
> And do you have any popup blocker plugins installed?

Huh! Although the add-on Ghostery did not show to block anything, deactiving it lead to the content of the cookie-preferences being displayed and the pop-up showing on the other pages...

Maybe include this info somewhere, too?

**Comment by mfranke93** [comment]
Okay. So everything should work as intended.

> Maybe include this info somewhere, too?

The question is, where? This is literally the first thing that a visitor **should** see, for GDPR reasons. I can look into whether it is possible to add some markup that tells popup blockers that this should not be blocked, but I can't make any promises.

**Comment by tutebatti** [comment]
I see. Weird thing is that it worked before, although Ghostery was enabled. I will keep an eye on that.

**Comment by mfranke93** [comment]
Okay, I have been able to reproduce the issue with Ghostery. Ghostery hides the cookie dialog, but not the background. I will add a small fix with `release/v1.1.3` that will also affect the background. Of course, that means that visitors with Ghostery installed will not be able to accept any cookies :shrug: for the public version, that only means they cannot create place sets, or save their view layout in the visualization. For the version at VIS, we have to keep this in mind when login issues appear.

**Comment by mfranke93** [comment]
And the cookie dialog issue with the visualization was an even easier fix: The visualization page did not load the script for the dialog :facepalm:
