### ISSUE TITLE
Map Glyphs missing in Google Chrome under Windows 11

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#141]
A visitor has just informed me that map glyphs are missing in their visualization:

![grafik](https://user-images.githubusercontent.com/7239968/167858569-3945583f-ce3c-4258-838e-ac80c5ded5e2.png)

They use Google Chrome under Windows 11.

**Comment by mfranke93** [comment]
I will need some more information, especially since I cannot test on Windows 11:

 - Browser version
 - Installed addons
 - Visualization state JSON
 - A screenshot of the developer console, in case there are any messages there

**Comment by mfranke93** [comment]
I see this happen in Edge (Chromium-based) in Windows 10 as well, though. So while the requested information would be nice to have for future issues, I don't need it now. I guess it is the same bug.

**Comment by tutebatti** [comment]
In the meantime, I have the exact browser version:  `101.0.4951.64 (Official Build) (64-bit)`

We should probably have a ready-made message for these cases (with additional explanations how to retrieve these informations for less skilled users). Is there anything else besides what you listed in the comment above that will be needed in such cases?

**Comment by mfranke93** [comment]
Good idea! I can't think of anything right now, but we can always extend it.

**Comment by mfranke93** [comment]
![scr](https://user-images.githubusercontent.com/9373678/168038623-beec2432-6564-49ba-be5b-7470fa17b32a.png)

Console in Edge 101.0.1210.39 (64-bit). The issue seems to be with the WASM-Code not allowed to load.

**Comment by mfranke93** [comment]
Possible fix: https://bugs.chromium.org/p/v8/issues/detail?id=7041

**Comment by tutebatti** [comment]
> Possible fix: https://bugs.chromium.org/p/v8/issues/detail?id=7041

I am not sure if this is something our visitor would fix on their machine or something the developers of chrome are at? Anyway, the visitor told me they can access _Damast_ using Firefox no problem. ;)

**Comment by mfranke93** [comment]
> I am not sure if this is something our visitor would fix on their machine

No, sorry, that was issue-related, so a note for me ;)

**Comment by mfranke93** [comment]
Fixed and deployed now, and the issue does no longer appear in Edge. Please reopen if it does in Chrome.
