### ISSUE TITLE
Easier and quicker access to generate reports

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#144]
One feedback was that it would be nice to have quicker/easier access to generate a report. I was thinking about some button in the corner of the map, but that's only a first idea.

**Comment by tutebatti** [comment]
[It seems I cannot change assignees, labels, etc. Tried in two browsers and in my own repository. Is that a bug of github?]

**Comment by mfranke93** [comment]
I have the feeling that it should not be *too easy* to generate a report. Putting a button or the like very prominently "in the front" might lead to a lot of unnecessary reports being generated *during* analysis or exploration, whereas the idea originally was to persist the analysis *at the end* of a session. 

Implementing this might cause a lot of load, maybe even too much, in the public version. Right now, it takes two clicks (and maybe half a second of scrolling) to generate a report. Does it really need to be quicker?

**Comment by tutebatti** [comment]
You can pause this for now, I'd say. If #147 is resolved, we will probably close it.

**Comment by mfranke93** [comment]
Implemented via #160
