### ISSUE TITLE
Very simple and short YouTube-Videos

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#149]
With the feedback by the visitor reported in #148 etc., the idea came up to make very short YouTube-Videos that do not cover a greater and complex research task as a whole, but answer small questions like: How do I look for a specific place?

As long as some users are overwhelmed by the documentation (which is systematic and not "problem-oriented") this might be a good solution.

**Comment by tutebatti** [comment]
@mfranke93 Is there a difference regarding terminology between the views and the areas/windows/panes in the visualization?

For example, in the following screenshot, one can see one view in each, well, what exactly? Subwindow?

![grafik](https://user-images.githubusercontent.com/7239968/168632533-ef9314bf-6f1d-4440-b79e-1b19f85ab912.png)

**Comment by mfranke93** [comment]
I think we called them "panes" in the other documentation.

The window is the browser window. I think it would be confusing to call anything else a window. "Subwindow" might work, or not. To stay consistent with the other docs: The visualization has multiple *panes.* Most panes contain a *view,* but the settings pane just contains some text and controls.

**Comment by tutebatti** [comment]
I'm on the right track making these videos. There should be no need for this thread. Will close and reopen if necessary.
