### ISSUE TITLE
Bring out religions (and confidence?) in timeline

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#150]
When moving the mouse vertically in the timeline, would it be possible to bring out the religion over the bar of which one is currently hovering? The feedback was that the broad scale of different colors is not easily matched comparing the timeline with the overview in the religion view.

A possible alternative is labeling the bars at the beginning of the timeline. That only works in qualitative mode, however.

**Comment by mfranke93** [comment]
My reply to this somehow disappeared...

So again: Yes, that is a good idea, and should not be too much development effort.

**Comment by mfranke93** [comment]
I implemented a first version. This considers the closest category vertically (important for situations with many thin strips), but with a cutoff distance. However, if the closest category is empty (e.g., religion has no evidence in that year) nothing is highlighted. It works for qualitative and quantitative modes, and for religion and confidence mode. Let me know whether the current behavior and highlighting are okay, based on the screenshots below (unfortunately they don't show the cursor, but it should be fine).

![image](https://user-images.githubusercontent.com/9373678/168622669-71c42801-bd43-4806-93d9-f7ebd9038be4.png)
![image](https://user-images.githubusercontent.com/9373678/168622625-0b95bc5a-d322-4083-8fbe-e68f19a01acf.png)
![image](https://user-images.githubusercontent.com/9373678/168623356-a82a8f68-b5ac-4051-a3eb-cb1a0a0f02ac.png)
![image](https://user-images.githubusercontent.com/9373678/168623476-fa9541b8-d8ba-4cac-a410-6d8bfe8142a4.png)
![image](https://user-images.githubusercontent.com/9373678/168623514-7424e67d-6f57-4f02-9778-eb12f80ffdb4.png)
![image](https://user-images.githubusercontent.com/9373678/168623555-631177aa-9776-4a64-b2eb-ccb2d4c97877.png)
![image](https://user-images.githubusercontent.com/9373678/168623583-98d34832-650c-4c49-8428-6c627fd9ddff.png)
![image](https://user-images.githubusercontent.com/9373678/168623605-595d7b27-b5df-48f5-95ae-cb8d6a3c4287.png)

**Comment by tutebatti** [comment]
Looks great, I'd say! :+1:

**Comment by tutebatti** [comment]
Can this be closed?

**Comment by mfranke93** [comment]
> Can this be closed?

![image](https://user-images.githubusercontent.com/9373678/174543638-06ebdfed-244f-4b9d-8415-53b85e8ce1cf.png)

**Comment by mfranke93** [comment]
You mean in the tooltip, right? Yes, I have thought about doing that as well, it should not be a large issue to add.

**Comment by tutebatti** [comment]
You implemented this already, haven't you? :)

**Comment by mfranke93** [comment]
> You mean in the tooltip, right? Yes, I have thought about doing that as well, it should not be a large issue to add.

That comment via e-mail took a **five-month detour** somehow... This was what I meant in https://github.com/UniStuttgart-VISUS/damast/issues/150#issuecomment-1127717138 by "reply disappeared".
