### ISSUE TITLE
Add a feedback form that is shown to visitors after some time

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#157]
Both for new features and data/domain opportunities (although GitHub issues are also available here) and for feedback to use in publications, it would be good to show a feedback form to visitors after some time, which they can optionally and anonymously fill out.

The following criteria should be met (@tutebatti please object if you disagree):

- [x] First, a dialog will be shown asking whether the visitors want to provide feedback, what that entails (anonymity etc.), and why it is needed. Here, visitors have the options "no, do not ask again", "not now", or "yes".
- [x] The feedback popup dialog will be shown after at least **20 minutes** of cumulative use of the visualization.
- [x] The feedback popup dialog will only be shown to visitors who have agreed for storage of at least **essential** cookies and data. The reason here is that cumulative use of the visualization and the fact the visitors did fill out the survey, or declined to do so, need to be stored.
- [x] In addition, a link to give feedback at any time will be added to the header, after the GitHub and license links.

Alternatively (@tutebatti, what do you think?) we could just add the link, and after some time show a small pop-up just notifying the visitors of the link. That would be less intrusive, but might result in less feedback as well.

**Comment by tutebatti** [comment]
I think the dialog with more text is good, i.e. not the alternative. Other than that, I have no objections. :smile:

**Comment by mfranke93** [comment]
Good to hear. For your information, this is what the first dialog looks like right now. I would keep it the same for when someone clicks the feedback link instead.

![Screen Shot 2022-06-22 at 11 25 19](https://user-images.githubusercontent.com/9373678/174994513-fc563139-4d8a-461a-9718-6cf9781805df.png)

**Comment by mfranke93** [comment]
First version of the questionnaire. Also including @kochsn for feedback.

![image](https://user-images.githubusercontent.com/9373678/175003212-44c9a694-7905-4300-a559-aecee1163801.png)

**Comment by tutebatti** [comment]
Looks good! I would print the first "Thank you" in bold.
