### ISSUE TITLE
Add the most important controls to more reachable places as well

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#160]
Some controls that currently are only in the settings pane could feasibly *also* be located in the respective view, or in the header. There, they would not have the description, but only a small tooltip with a brief description and a reference to the settings pane for more details.

The question (@tutebatti, @kochsn) is which controls this pertains to. My suggestion:

- [x] All of the "modes":
  - [x] Show all/only active (header)
  - [x] Religion/confidence mode (confidence view)
  - [x] False coloring (cf. #158) (religion view)
  - [x] Timeline mode (timeline)
  - [x] Clustered/unclustered map (map)
- [x] All of the other controls, except for the layout:
  - [x] Describe filters (header)
  - [x] Generate report (header) (maybe show a warning first that this should not be abused) (this issue then supersedes #144)
    - [x] Add control
    - [x] Add warning
  - [x] Download state (header)
  - [x] Load state (header)

As I said, the controls would still be part of the settings pane as well, with the detailed description. So, there would be two places where these can be controlled. For the header, it would just be five small buttons, next to where the history graph controls already are (see Damast @ VIS for what I mean):
![image](https://user-images.githubusercontent.com/9373678/175293761-8f90edfe-9475-41ca-818e-3c280562fa33.png)

Please let me know what you think :smile:

**Comment by tutebatti** [comment]
This is grand! I like it. However, I would seperate them spacewise in the header, so the controls of the visualization are distinguished from the overall menu of the entire page ("Webpräsenz").

**Comment by mfranke93** [comment]
> I would seperate them spacewise in the header, so the controls of the visualization are distinguished from the overall menu of the entire page ("Webpräsenz").

Yes. That is already the case for the history controls (see screenshot), and I would do the same with the rest of the controls. It is not going to be very much space, though. There are a lot of items in the header now, and I have already started shortening it down (remove the copyright notice, it is in the license anyways) because I suspect the header has two rows on smaller screens otherwise, which is not ideal.

**Comment by mfranke93** [comment]
I have now implemented most of it, although I still want to add a confirmation dialog before report generation is actually started:

![image](https://user-images.githubusercontent.com/9373678/175813348-50d31c2b-5969-4cc0-86bb-da4dfcdef62b.png)

**Comment by tutebatti** [comment]
Great!
