### ISSUE TITLE
How to deal with Ghostery?

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#162]
From https://github.com/UniStuttgart-VISUS/damast/issues/147#issuecomment-1167605334
> Just another remark: On the testing server, before logging in, I have the same problem as https://github.com/UniStuttgart-VISUS/damast/issues/139 while the Add-on "Ghostery" is active.

Quick point: no, it is not the same issue. At least not on my end. It is just that all input elements (buttons, login form, ...) are disabled while the cookie dialog is showing (even if Ghostery "hides" it, it just does so via CSS and does not remove it from the DOM). The disabling of other elements is by design, so that you could not tab or click outside the dialog, or be shown login suggestion popups, while it is open.

But of course, this now runs into issues with the visualization when Ghostery is active. There are two courses of action:

1. Warn visitors that their plugin causes issues. Show a warning *instead* of the normal page content, let them disable Ghostery and reload.
2. Let visitors shoot themselves in the foot. Just quietly accept that the cookie popup is getting banished by Ghostery, and let them use the page as usual. Not everything will work as expected, but it will seem as if it does on the first sight.

Honestly, I would tend towards **2.** It is easier to implement and leaves us with less work long-term if the popup blockers change. But please, @tutebatti, let me know what you think.

**Comment by tutebatti** [comment]
I would go with 2., too. Any user uses add-ons at their own risk.
