### ISSUE TITLE
Views not updating when no data matches filter?

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#164]
I have just tried to reproduce the more complex search modifying the place set as described in the docs at the end of [this section](https://damast.geschichte.hu-berlin.de/docs/vis#location-list). We added this:

>  Note: The map is blank; this is normal as you have just filtered out all places with presence of Judaism while the religion view is still set to show Judaism only. 

However, this seems not to work anymore, I tried both with Firefox and Chromium. If you go the last step of that example described by the docs, it works. However, if you then change the _Religions_ filter again to Judaism only and click "Apply", nothing happens. (Note: The Apply button is not greyed out; and of course, it shouldn't be, because I changed the filters back from Christianity to Judaism.)

I assume it has to do with no data chosen whatsoever? E.g., if I chose in the _Sources_ view "TIB 15" only (with no other filters active), I get 41 placed and 0 unplaced locations. If I then choose only "Others" in the _Religions_ filter, I expect nothing to be shown (because TIB 15 wouldn't cover any subgroup of OTH). However, the visualization just stays as is.

**Comment by mfranke93** [comment]
> I assume it has to do with no data chosen whatsoever?

In a way, yes. This triggered a bug with the new false-color scale. It is generated so that the colors are as distinct as possible, for the current number of religious groups shown. But it did not handle the case of "0 religious groups" very well... It will be fixed in the next release.
