### ISSUE TITLE
Showing year when filtering in timeline.

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#165]
Is there a possibility to see more precisely at what year one is with the cursor when choosing a timespan in the the timeline drawing this rectangle?

**Comment by mfranke93** [comment]
Not yet, no. For the start year, one could use the tooltip. But that disappears with the mouse-down... I think that would be a good addition!

**Comment by mfranke93** [comment]
The start and end year are now shown as follows, with small arrow ticks where the other x-axis ticks are:
![image](https://user-images.githubusercontent.com/9373678/184875518-3c8eea6b-3e5e-44fb-80eb-da835916a095.png)

The usual number labels are hidden if they would overlap with the new start and end label. In the main timeline, the labels are only shown if within the visible range, but if not, both are show in the overview timeline in any case:
![image](https://user-images.githubusercontent.com/9373678/184875883-5ace54ed-5ce3-4eed-a32d-208f5cf2e29d.png)

The new labels are placed left (start) and right (end) of the tick, in case they are close together:
![image](https://user-images.githubusercontent.com/9373678/184876283-c8771add-0939-4a87-84c8-c69f24bbea48.png)

If both are the same year (virtually impossible to see before this) it looks like this:
![image](https://user-images.githubusercontent.com/9373678/184876735-36a700a5-908e-482c-9a9b-fdb39f1ae3c5.png)
