### ISSUE TITLE
Tooltip of tags

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#17]
In the _Tag view_, is there a possibility to add tooltips to the tags? This might not be needed for many of the tags planned for the public version as the tags used here are self-explanatory. However, it could be of use when thinking of other tags.

**Comment by tutebatti** [comment]
This should probably be paused until all info texts are rephrased to their final state, including correction of the English by a native speaker. Then, all tooltips in all views should be checked against the info texts.

**Comment by mfranke93** [comment]
This would mean adding a new column to the `tag` table (called `description` or something similar). That would then be shown in the tooltip if it is not empty.

**Comment by tutebatti** [comment]
I suppose you refer to the <tag> table in the database, not the view. I just had a look at this table. It does contain a column called <comment>, which actually seems to function as a description. Depending on what @rpbarczok thinks, we could just use this column and change specific contents of the columns, if necessary.

**Comment by mfranke93** [comment]
Yes, I referred to the table. I interpreted the issue as such: "Add a description of what the tag means to the tooltips in the tag view", because these tooltips already exist:
![image](https://user-images.githubusercontent.com/9373678/148749346-adc13ea3-35ea-4654-b20b-502dd04f9580.png)

If each tag needs a specific text, the obvious place to store it would be in the `tag` table, then. The formatting in your comment messed up somehow, but I assume you meant the `comment` column. We can use that, of course, or add a dedicated column if both could be needed separately.

**Comment by tutebatti** [comment]
What I had in mind was the respective handling in the __Source view__:
![grafik](https://user-images.githubusercontent.com/7239968/148750220-a00d558d-50d3-4bee-9218-69ae9fc169d2.png)

**Comment by mfranke93** [comment]
I am not sure what you mean here, in relation to the tag view. In the source view, you see the long name of the respective source in the tooltip, and below that the distribution of the contained evidences on the religions.

**Comment by tutebatti** [comment]
Where the "long name" of the source is displayed in the tooltip of _Source view_ is where the "comment" of the tag should be displayed in the _Tag view_ (or, if @rpbarczok thinks that's better, the description that then needs to be added).

**Comment by rpbarczok** [comment]
In the comment column I already entered a short description. We should of course proof read these comments, but then they can easily be used as description, in the way Florian suggests

**Comment by tutebatti** [comment]
Great! Thank you. I will proofread them and record my suggested changes (just in case).

**Comment by mfranke93** [comment]
Great. My suggestion would be that I implement it for v1.0.4 (#42). The necessary data should be in the frontend already, so it really is a minor tweak. Then you can check if they fit directly from the visualization as well.

**Comment by mfranke93** [comment]
Note: The `comment` entries might need a period (.) at the end where they are not empty:
![image](https://user-images.githubusercontent.com/9373678/149917759-baa84d8c-97ab-4118-9556-7273bb426d40.png)
