### ISSUE TITLE
fix minor documentation issues

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#176]
- [x] The table descriptions in the PDF documentation do not match the layout. In the README, each field has its own column, but in the PDF, the first three columns are represented as rows of the first column.
- [x] `util/README.md` says `pg_dump` instead of `ro_dump`
- [x] `util/README.md` links to a no longer existing `roles.md`, but should instead reference the PDF documentation.

**Comment by revanthsonu** [comment]
Can I work on this?

**Comment by mfranke93** [comment]
> Can I work on this?

To be honest, I don't think the scope of the necessary changes is large enough to be worth it: It is already clear what needs to be changed and how, the only open task is to check for consistency in the rest of the documentation around these sections. That requires some experience with the docs and with Damast. I know I put in the **good first issue** label, but that was more aimed towards collaborators that are already familiar with Damast and the docs.

As it stands, I will probably just do it myself. But thank you for asking!
