### ISSUE TITLE
Migrate to a newer Tabulator (5.4) version

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#187]
https://www.tabulator.info/docs/5.4/upgrade

**Comment by mfranke93** [comment]
Save for the general v4 -> v5 migration, the smaller changes between versions have been dealt with. However, [a lot](https://www.tabulator.info/docs/5.0/upgrade) is changing with the major version change, which makes some larger restructuring necessary in our code. We (@tutebatti) should discuss if we have the capacity to do this upgrade, as it would need to be tested thoroughly before merging.

**Comment by tutebatti** [comment]
Feel free to schedule something to discuss this anytime.
