### ISSUE TITLE
Implement subpage with contact form

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#19]
There should be a separate subpage with a contact form. For the purpose of the public instance at HU, I would suggest the following fields, which are, however, more or less generic:
- name
- e-mail
- message
Probably, there should be some mechanism against bots?
The message should go to a predefined e-mail address.

The plain text written above the form needs to be adapted to the respective purpose, e.g. the public instance at HU.

**Comment by mfranke93** [comment]
Adding a mail server to the Damast system/code is outside the scope of the project, I think. Beside everything that has to be considered security-wise, it is just a lot of extra implementation work with little added value. There are three ways this could be solved that make more sense:

1. Add an e-mail link (`mailto:...`) at the appropriate place. Clicking such a link already opens the user's mail application with the address pre-filled by default. This would be very little work, and only in the front end (HTML). 
2. Link to a more general page for contacting; that is, not on `dhimu.hist.hu-berlin.de` (or similar), but at `hist.hu-berlin.de`, where such a contact form (and back end mail server) already exist.
3. Run a mail server and a HTTP server just for the contact form and mail sending *alongside* Damast on the host system where the Damast Docker container runs. Integrate the contact page via the configuration of the (nginx) reverse proxy that would run on the host system anyways for SSL (reference the infrastructure schema I sent you earlier).

**Comment by tutebatti** [comment]
Thank you for clarification. Option 2 (along with option 1) seems very feasible.
