### ISSUE TITLE
URL to Volkswagen Logo outdated

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#192]
The URL to the logo in https://github.com/UniStuttgart-VISUS/damast/blob/main/damast/root/templates/root/index.html is not up to date:

https://www.volkswagenstiftung.de/profiles/vwst/theme/volkswagen/images/logo.svg

Possibly use this one: https://de.wikipedia.org/wiki/Datei:Logo_Volkswagenstiftung.svg ?

**Comment by mfranke93** [comment]
I believe the originally linked one was the light one, which has better contrast to the dark background of the home page. Maybe this one:

https://www.volkswagenstiftung.de/themes/VWS/media/images/logo-vwstiftung-light.svg

Having a WikiMedia one would be nice, because the URLs are more stable, but I don't know if there is a light one. Alternatively, one could use the dark one and do some CSS magic to get it white (`filter: saturate(0%) invert(100%) lighten(300%)` or something along those lines).

**Comment by tutebatti** [comment]
I will give at a shot. Would you assign me? I will also try and see if the other logos can be replaced by the ones possibly on WikiMedia.

**Comment by kshitiz305** [comment]
I would like to work on it

**Comment by mfranke93** [comment]
> I would like to work on it

@tutebatti asked to be assigned first, but you can coordinate with them. A word of warning though, ideally the changes necessary by this issue would at least be tested and verified locally, which requires some prior knowledge of the project.

**Comment by tutebatti** [comment]
The background where the logos appear is white. I simply substituted the img source using the developer tools in the public version and it looks fine to me.

https://upload.wikimedia.org/wikipedia/commons/2/21/Logo_Volkswagenstiftung.svg

In addition, the one by the DFG should better be:

https://upload.wikimedia.org/wikipedia/commons/8/86/DFG-logo-blau.svg

**Comment by mfranke93** [comment]
> The background where the logos appear is white. I simply substituted the img source using the developer tools in the public version and it looks fine to me.

Right, I forgot the start page changed design...

> In addition, the one by the DFG should better be:
>
> https://upload.wikimedia.org/wikipedia/commons/8/86/DFG-logo-blau.svg

I completely agree. I just took the one used for the project page at the Goethe-University at the time.

**Comment by mfranke93** [comment]
While we're at it, we might as well replace all image sources with WikiMedia:
https://commons.wikimedia.org/wiki/File:Uni_stuttgart_logo.svg
