### ISSUE TITLE
Include section "How to Cite" in each overview page of a place

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#2]
*Initially opened by gs108488 in [207@TIK](https://github.tik.uni-stuttgart.de/frankemx/damast/issues/207). History:*

**gs108488** Dec 9, 2021:

> I suggest to include a remark such as the following at the top of each place page or below the table at the right side:
>
> "This page or place description can be accessed via its persistent URI (xyz), which includes its UUID (?) xyz. This follows the principle of Linked Open Data (LOD)."
>
> I know this is obvious for many, but will help certain others a lot. If there are errors in the exact phrasing of my suggestion, feel free to change that, of course.

**frankemx** Dec 9, 2021:

> You mean [here](https://www2.visus.uni-stuttgart.de/damast/place/310), right? What do you mean by UUID?

**gs108488** Dec 9, 2021:

> Yes, for example on such a page as the one of Abaskun. With UUID I meant the unique id of the respective place, so here for Abaskun it's 310.

**frankemx** Dec 9, 2021:

That would be the place *ID*. A UUID is a [special kind of unique ID](https://en.wikipedia.org/wiki/Universally_unique_identifier) that looks like this: `5747c047-3662-11ec-9dea-534c80687e57`.

Sure, I can add that to the page. However, the URI is already in the table:
![image](https://user-images.githubusercontent.com/9373678/147079789-81b55c3e-4e2d-4f3e-b92b-980bae59b148.png)

Redundancy doesn't hurt, but should I remove it there? 

**gs108488** Dec 9, 2021:

> Thanks for clarification, once again lesson learned. I suggest to move the URI to the last line of the table and put the sentence below the table or in a new line like this:
> 
> "This page or place description can be accessed via its persistent URI (see above), which includes its ID xyz. This follows the principle of Linked Open Data (LOD)."
> 
> Again, corrections or improvements to that phrase are more than welcome.
> 
> Question \@gs106810: Should we include a link to some place explaining LOD (e.g. https://www.w3.org/wiki/LinkedData) or leave it to the visitor to google that.

**frankemx** Dec 9, 2021:

> The other issue I see is that LOD kind of implies RDF or semantic web as a data format, which we do not provide. Maybe that should be clarified as well.

**gs108488** Dec 9, 2021:

> This is an issue, yes, but "kind of implies" probably means that LOD *ideally* includes RDF, but not necessarily (https://en.wikipedia.org/wiki/Linked_data#Principles, "should", not "must"). Again, I would like to hear Ralph's (\@gs106810 ) opinion on that, maybe we should rephrase that sentence.

**gs106810** Dec 9, 2021:

> I would agree with Max, LOD indeed imples RDF or semantic web, I don't think we have to mention that explicitly. By including our project in the Hist-ME group and the World historical gazatteer, we become a part of the LOD in a passiv way. At least, that was my idea. 

**gs108488** Dec 9, 2021:

> Ok, I see. Still, the non-technical users should be made aware that the URIs are persistent and can be used in such a way. Any suggestions for rephrasing the sentence in a fitting way?

**gs106810** Dec 9, 2021:

> I would suggest that we offer a similar citation suggestion as other projects do. E. g. the HIMME project has a section "How to cite this entry". The example for Aleppo (https://medievalmideast.org/place/5514.html) is: "Thomas A. Carlson, et al., “Aleppo” in Thomas A. Carlson, ed. Historical Index of the Medieval Middle East, last modified September 16, 2021, https://medievalmideast.org/place/5514." . 

**frankemx** Dec 9, 2021:

> Sounds good to me. Thank you! We should discuss the exact phrasing (who is named, e.g.) with Dorothea and Steffen in January.

**Comment by tutebatti** [comment]
I renamed the issue. Following points/questions:

- What is the correct term for "overview page of place" that I used in the new issue title? We will have to refer to this in the start page as well as some info texts and the documentation.
- Where would I suggest what the section needs to look like? This is not as easy compared to changing the html of the info texts, is it?
- What is more, I am not sure who the "authors" of a report are when it comes to citation. Probably, instead of some standard bibliographical data, it should be something like:

> We suggest to cite this report in the following way: "Report ###UUID### created by ###YOUR NAME### based on the visualization and data of Weltecke, Dorothea et al. "Dhimmis and Muslims. A Tool [...]" accessible via ###URI###."

**Comment by mfranke93** [comment]
> What is the correct term for "overview page of place" that I used in the new issue title? We will have to refer to this in the start page as well as some info texts and the documentation.

Until now I always referred to it as the "place URI page", because that is where the URI for a place in our namespace links to. Maybe you (@rpbarczok, @tutebatti) know a nicer term for this, maybe from other projects?

> Where would I suggest what the section needs to look like?

The same as with the info texts, I would suggest we make a branch for that, and issues. If it is more than just adding or editing text (see below), of course I can help.

> This is not as easy compared to changing the html of the info texts, is it?

Depends. It is a bit more Jinja2 logic than the info texts, but if it only concerns the text content formulation, it is probably not harder. If there needs to be more or different content fed into the templates from the database, the backend code needs to be modified as well, and I suppose that would be something I need to do. Similarly, if styling and layout changes are necessary, the CSS for the page needs to be touched as well.

**Comment by mfranke93** [comment]
> Could you point out the file(s) (including path) that generate the html of the "place URI page"?

[https://github.com/UniStuttgart-VISUS/damast/blob/main/dhimmis/uri/place.py](Python), [HTML](https://github.com/UniStuttgart-VISUS/damast/blob/main/dhimmis/uri/templates/uri/place.html) and [CSS](https://github.com/UniStuttgart-VISUS/damast/blob/main/src/scss/uri.scss).

**Comment by tutebatti** [comment]
Here, too, as in #56, the form of the reference should be final, with the exception of "DAMAST" (appearing once), which might be changed to title case later.

**Comment by mfranke93** [comment]
see [here](https://github.com/UniStuttgart-VISUS/damast/issues/56#issuecomment-1029006033)

**Comment by tutebatti** [comment]
This looks good:
![grafik](https://user-images.githubusercontent.com/7239968/152363387-c814ec49-04d9-4ef8-8940-d386f071394a.png)
