### ISSUE TITLE
What does "source instance" mean as against "source"?

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#20]
While rephrasing the info text, regarding the Source view, I came across the following sentence: 

> Keep in mind that an evidence tuple can have multiple source instances. As long as <em>any</em> source instance's source is checked in this view, the evidence tuple will be active.

What does "source instance" refer to here?

**Comment by mfranke93** [comment]
A source instance is the connection between one evidence and one source (see [the database schema](https://www2.visus.uni-stuttgart.de/damast/docs/schema)). Such intermediate tables are often necessary in relational databases (such as PostgreSQL) to model one-to-many or many-to-one relationships. We further use these tables (source instance, person/place/religion instance) to store metadata such as comments and confidence.

Historically, we had evidences from more than one source. Now, this is cleaned up. and the only cases where this applies is if there are multiple translations of a source in the database (such as Muqqadasī). @rpbarczok can say more about how the sources are handled.

The existence of this table (or concept in the data model) is probably not something that visitors need to know when looking at the visualization. Still, I think it is important to communicate that evidences do not always associate with just **one** source, and therefore

 1. an evidence could show up in two different filters on the sources, even if those filters are completely disjunct, and
 2. the sum of the bars in the source view could add up to more than the number of evidences.

**Comment by tutebatti** [comment]
Thank you. I will try to rephrase that accordingly.
