### ISSUE TITLE
"No value" in Confidence view and respective info text

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#21]
While rephrasing the info text for _Confidence view_, I'm trying to figure out why "no value" is used. As far as I can see from the current productive version of damast, which includes the eOC data, the respective evidence tuples with "no value" are probably from new data not fully documented?

In case there is no data planned to be included in the public version that has "no value" for any confidence while that line in the Confidence view is still present, the info text still needs to explain why this is. In that case, something like this could be stated:
> The attribution with "no value" is used while data is still being collected and usually does not appear in a published instance of this visualiziation.

**Comment by mfranke93** [comment]
Adding something like this would be good. I think the goal was not to have any data without confidence for the public version anyways. However, completely removing the row would be a divergence again (#8), because it is still necessary in the production version.

**Comment by tutebatti** [comment]
Exactly. I wait for any comments, especially by @rpbarczok, to rephrase the suggested addition (this is part of #6). Otherwise it can be included.

**Comment by rpbarczok** [comment]
>  I think the goal was not to have any data without confidence for the public version anyways.
There is one case in that we will have "no value" in the public version: In the case that we do not have geocoordinates for a place, the assignment of a confidence does not make any sense, so there is no value.

**Comment by tutebatti** [comment]
@rpbarczok So, how many of the currently ca. 370 places with "no value" will remain in the public version? For the other aspects, we have about 390 each with "no value". Looking at the List "Unplaced" in the _Place view_, DhiMu data contains 20 of them.

**Comment by rpbarczok** [comment]
Most cases of geographical names without geo-coordinates are within the Oriens Christianus Novus (because many dioceses are named after regions and not places) and are not relevant to the DhiMu. So there will be only the 20 places that are listed under "unplaced"

**Comment by tutebatti** [comment]
Thank you. So these 20 will remain. I will phrase the text accordingly.
