### ISSUE TITLE
Add GeoJSON export function to visualization

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#231]
Add a button to download a GeoJSON file with the currently visible locations.

To be determined:
- What other data attributes should be included?
  - At least the infobox data from the place URI pages
  - Religious groups
  - Temporal data
  - Active filters
  - Links to other repositories for each place
  - Alternative names
- How granular should metadata selection be on export?
  - One download button
  - Menu with checkboxes for different attributes (religious groups, alternative names, ...)

**Comment by mfranke93** [comment]
After some thought, I implemented it as follows, using the data collection code already in place for report generation:
- There are two alternatives for the GeoJSON file that is produced: With and without details.
  - In both cases, the GeoJSON contains a set of `Point` `Feature`s. In the `properties` of the `FeatureCollection`, some metadata about the Damast instance, the time the file was generated, copyright, and the filters applied to get that specific set of places are stored.
  - **Without** details, the `Point` `Feature`s only contain the position, the base name, and a reference to the full place URI page (e.g., https://damast.geschichte.hu-berlin.de/place/14).
  -  **With** details, the `properties` of each place feature also contain alternative names, links to external URIs (e.g., Syriaca), and the relevant (filtered) pieces of evidence for that place (time spans, religious group, ...).
- Places without a location are placed at N 0°, E 0° (Null Island). While leaving the coordinates empty is allowed under the GeoJSON specification, all tools I tried to open such GeoJSON files with failed. Instead, these places' properties have a property `has_coordinates: false`, a `scale_rank=100` (places with geolocation have `scale_rank=0`), and the `location_confidence=null`.
- The version *without* details can be accessed from a button in the header, where the other shortcuts (history, generate report, describe filters, ...) are as well.
- Both versions (with and without details) can be accessed from the settings pane.
- If the generated GeoJSON file contains ≥100 places, a confirmation dialog is shown first, similar to when trying to generate a large report. Generating a version containing the entire dataset takes a few seconds, and should only be done intentionally. This should hopefully avoid bad user experience.
- All of this is also documented both in the web page and PDF version of the documentation.

@Schoeneh I have sent you credentials to our testing instance, where this feature has been deployed. If you could test it out a bit and provide feedback, that would be great!

**Comment by mfranke93** [comment]
Note to self:  The URLs in the exported GeoJSON still have some issues with the base URL behind the reverse proxy:

- [ ] In the metadata, in the `how_to_cite`, the URL should be `.../damast/testing/`, but the path at the end is missing.
- [ ] In the URI of the places, the path is present twice (`.../damast/testing/damast/testing/place/...`).

**Comment by Schoeneh** [comment]
I already found a weird occurrence/bug:
At one point got transported to null-island...
https://box.hu-berlin.de/f/d5dcf79bbcba4edd993e/
![grafik](https://github.com/UniStuttgart-VISUS/damast/assets/116974162/2a8bae3e-bd58-466b-a5ab-7fd87d8b4b0a)

**Comment by mfranke93** [comment]
> And shouldn't the file extension be ".geojson" instead of ".geo.json"?
> (it works fine either way, but I'm used to the former and have never seen the latter)
> The specification says: "File extension(s): .json, .geojson" https://datatracker.ietf.org/doc/html/rfc7946
I can change it to .geojson. I think I chose .geo.json because it gets recognized as a JSON file, whereas .geojson files sometimes were opened with the wrong tool...

**Comment by mfranke93** [comment]
> But having places without location data mapped to null island really messed with my experience - maybe an alternative solution could be feasible?

I'm not happy with the Null Island, either. The RFC suggests `"coordinates": null`. Does that work with QGIS?

GPXSee (which is what I had installed and what opened the files by default) complains both with `[null, null]` and `null`, and shows none of the other data either.
[geojson.io](geojson.io) complains for `null`, but shows the other data points. For `[null, null]`, it just internally converts it to `[0,0]` again, it seems...

Doing `"coordinates":null`, as suggested by the RFC, would be my preferred solution. Please let me know whether that works in QGIS.

**Comment by Schoeneh** [comment]
@mfranke93 `"coordinates":null` is no problem for QGIS.

**Comment by mfranke93** [comment]
Alright... I'll try to implement that by end of week. Since I need to change the documentation again, unfortunately, it's not a one-line fix :grin:

**Comment by mfranke93** [comment]
@Schoeneh it seems I slightly misinterpreted the RFC. See [section 3.2](https://www.rfc-editor.org/rfc/rfc7946#section-3.2), it should be `"geometry": null` and not `"geometry": { "coordinates": null, "type": "Point" }` (which makes more sense when I think about it. I just tested that with geojson.io, and it complained less than with the `"coordinates": null` variant. I would guess QGIS would be happy with that as well, but could you maybe quickly check?

**Comment by mfranke93** [comment]
``` geojson
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          22.477044718122045,
          15.207017869893832
        ],
        "type": "Point"
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": null
    }
  ]
}
```

**Comment by Schoeneh** [comment]
Yeah, `"gemeotry": null` makes much more sense :)
Using your test file, QGIS did not complain - everything is fine.
