### ISSUE TITLE
Linking inside and between info texts

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#33]
Is it possible to link to other sections of the same info text or even info texts of different views/panes?

**Comment by mfranke93** [comment]
Very hard, at least the way they are implemented right now. For one, they can be displayed in an entire separate window, where there would be no context at all. Also, they are shown in a modal/dialog window, which means that nothing else on the page can be clicked or used while the modal is open.

If there is need for info text that concerns more than one view, I would suggest putting it somewhere else. The info texts for the views were always meant to be very specific to the view. They were also never meant to be that long and detailed.

**Comment by tutebatti** [comment]
Ok, I thought that the implementation as modal windows will be a problem here. I think it is sufficient to use textual pointers such as "(cf. the _Settings pane_).

However, if you (or @rpbarczok ) think that the info texts become to long and detailed as modals, we should think about having an extra page with all the explanations. (There, linking between sections would not be a problem, right?) Personally, I find the modal windows great.

**Comment by mfranke93** [comment]
Not a problem at all. In that case, we could also do it like this:

 - Each view's info text

**Comment by tutebatti** [comment]
I would pause this until we have feedback from "fresh" users who haven't used the visualization at all and who will look at the info texts.

**Comment by tutebatti** [comment]
This seems resolved to me once #46 is resolved. Closing.
