### ISSUE TITLE
Consistency in using <em> or any other typographical features in info texts

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#37]
Rephrasing the info texts, I wonder in what way highlighting, e.g., using `<em>` should be used. I would like to reserve quotation marks (using `<q>`) for scare quotes (cf. https://en.wikipedia.org/wiki/Scare_quotes). Of course, some elements need to be highlighted to draw attention. `<em>` makes sense in that case. What would you suggest to use when referring to other elements that are part of the visualization, e.g., _Settings pane_? Is there something similar to `this typography for code` for that?

**Comment by mfranke93** [comment]
I agree about the quotes. Regarding referring to other elements, I wouldn't use `code` typography (`<code>code</code>`) for those and reserve that for technical terms (such as `localStorage`, see the Settings pane text). I have tried to be consistent with using `<em>` for terms that are meaningful/important in the visualization, such as *Confidence mode*, as well. Is there an issue with just using `<em>` for both?

**Comment by rpbarczok** [comment]
I agree with Max.

**Comment by tutebatti** [comment]
Rephrasing the info texts (which will need to be checked and corrected anyway), I sometimes use multiple terms in `<em>`-tags to refer to phenomena of the visualization. In a context like that, a term that needs to be highlighted does not come out clearly. Still I see why `<code>` is not a good choice. What about highlighting by using **bold**, keeping <em> for the vis. phenomena?

**Comment by tutebatti** [comment]
Very good! What do you say, @rpbarczok?

**Comment by rpbarczok** [comment]
I agree with Max. The basic rule is to use semantic tags.

**Comment by tutebatti** [comment]
Now that I see my changes in the running instance, I realize that the tag `strong` leads not only to bold but also to a font in a different color. I find that too much for the aspects I wanted to highlight. Still, I would like to distinguish elements of the visualization from things that are highlighted. Would you object using a bold font in the same color?

**Comment by mfranke93** [comment]
> Would you object using a bold font in the same color?

Not at all. I agree that for the way the `<strong>` tag is used *now,* it is too much. Initially, there were other uses of it where it made sense, but I can't find any of those still left in the info texts. Just put me in a ticket with the relevant infos.
