### ISSUE TITLE
Questions about features of timeline graphs

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#38]
I here want to double check, if I understood the different features of the timeline with its two graphs correctly.

**First**, the following applies to both graphs or the timeline in general:
- Hovering will display the evidence tuples of that year, depending on religious or confidence view.
- They both react

(1) to brushing and linking through a selection in another view. This is what I get from using the visualization. However, in the current info text, what I don't understand regarding the lower graph:

> This overview does not change during brushing or zooming [...]

(2) to changing "All data" to "Only active" in the settings. The following sentence from the current info text I don't understand: 
> The time filter does itself not influence the timeline for efficiency reasons.

**Secondly**, the two graphs have also each different features/functions.
The _upper graph_ 
- is used for filtering according to time.
- changes depending on qualitative and quantitative timeline.
- changes colours in all data mode.

The _lower graph_
- is used as a minimap of the upper graph: One can click and drag a section to "zoom in" on the upper graph; also, when filtering via the upper graph, the selected timespan is indicated by a bar beneath the lower graph.

Please add anything I forgot and correct.

**Comment by mfranke93** [comment]
Can you please check the formatting of your description? I am not quite sure how to read it and which bullet points belong together.

**Comment by tutebatti** [comment]
Edited. There seem to be no list hierarchies here...

**Comment by mfranke93** [comment]
Thanks. As far as I know, Markdown allows for nested lists, but you have to be quite precise with the syntax (empty line inbetween, correct indentation).

> First, the following applies to both graphs or the timeline in general:
> - Hovering will display the evidence tuples of that year, depending on religious or confidence view.

Yes. Hovering over the timeline will show a tooltip with information about the year. However, I have an issue with the "applies to both graphs" here. That is what happens, yes, but IMO that is a bug. The lower overview graph can have a different scaling when the upper one is zoomed in, and then the tooltip does not match what is below the cursor when hovering over the overview timeline. I have filed this as an issue (#39), but I'm not decided on what the final behavior will be.

> However, in the current info text, what I don't understand regarding the lower graph:
> >  This overview does not change during brushing or zooming [...]

Yes, that is historical again and should be updated. The overview does **not** change during zooming. So, if you select a shorter time period in the overview, which is then shown larger in the upper timeline, the overview's extent does not change. This is important to be able to zoom out etc. **However,** the overview *does* change during brushing now. If you click on (brush), for example, a religion, the overview also shows (links) that religion.

> - They both react
>    (2) to changing "All data" to "Only active" in the settings.

Yes.

> The following sentence from the current info text I don't understand:
> > The time filter does itself not influence the timeline for efficiency reasons.

Again, historical. This sentence can just be removed. In previous, versions, the timeline would stay unchanged when selecting a time span. Now, it also shows the filtered data.

> Secondly, the two graphs have also each different features/functions.
> The upper graph
>
> - is used for filtering according to time.
> - changes depending on qualitative and quantitative timeline.
> - changes colours in all data mode.
>
> The lower graph
>
> - is used as a minimap of the upper graph: One can click and drag a section to "zoom in" on the upper graph; also, when filtering via the upper graph, the selected timespan is indicated by a bar beneath the lower graph.

Yes.

> Please add anything I forgot and correct.

I don't notice anything missing off the top of my head, but the rest should be in the current version of the info text.

**Comment by tutebatti** [comment]
Thank you for clarification. For now, I will rephrase the info text matching the current behaviour. Once the bug is resolved, it can be adapted.

**Comment by tutebatti** [comment]
> The overview does not change during zooming. So, if you select a shorter time period in the overview, which is then shown larger in the upper timeline, the overview's extent does not change. This is important to be able to zoom out etc.

"Zooming" here refers to zooming in the map or in the timeline?

**Comment by mfranke93** [comment]
The timeline; i.e., selecting a time span in the *overview* timeline.

Zooming in the map does *not* affect data filters in any ways or trigger any recomputations, except for the clustering of map symbols.

**Comment by tutebatti** [comment]
Ok, I thought so. Still, this is very misleading if not specified. Thus, "in the timeline" should always be added to "zoom(ing)".
