### ISSUE TITLE
Description of glyphs in current info text of map

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#40]
The current info text of the map reads in one place (referring to the default, clustered mode):

> On mouse-over, the glyphs lose opacity, and the aggregated locations are indicated on the map. The represented data is further linked in other views. The aggregation level of locations depends on the zoom level, such that the glyph scaling is constant. 

I assume "the aggregated locations are indicated on the map" is not true anymore (i.e., historical).

Also, the statement "represented data is further linked in other views" is now true not for _mouse-over_ but for _selecting_ the glyph by clicking on it.

However, a tooltip is shown when hovering over a glyph, which also lists the places aggregated into the single glyph.

Please correct where necessary.

**Comment by mfranke93** [comment]
> I assume "the aggregated locations are indicated on the map" is not true anymore (i.e., historical).

No. That's exactly what happens:
![image](https://user-images.githubusercontent.com/9373678/149340751-56a56ff9-d1d6-4a69-a674-c06ca1000df5.png)

> Also, the statement "represented data is further linked in other views" is now true not for mouse-over but for selecting the glyph by clicking on it.

Yes.

> However, a tooltip is shown when hovering over a glyph, which also lists the places aggregated into the single glyph.

Yes.

**Comment by tutebatti** [comment]
I see! I had tested it like so, however the points are hardly visible:
![grafik](https://user-images.githubusercontent.com/7239968/149341916-e7a48b5a-da73-4b29-a70e-bbf233b4407e.png)

Maybe the dots should be red or the like rather than blue? Even in your screenshot I mistook them for water.

**Comment by mfranke93** [comment]
They are not meant to be super visible, and since they need to be quite small, finding a color that is visible on every background is hard/impossible in any case.

**Comment by tutebatti** [comment]
Ok. Still, I will specify that

> the aggregated locations are indicated on the map __as small blue dots__

Correct?

**Comment by mfranke93** [comment]
Turquoise dots, I think. But yes.

**Comment by tutebatti** [comment]
Or even __as small turquoise dots that may be partially covered by the glyph__.
