### ISSUE TITLE
Behaviour of Placed and Unplaced lists in Location view

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#50]
Currently, the info text of the Location view reads in one place:

> In _Only active_ mode, only the brushed locations are listed.

What is meant or what it should be:

> In _Only active_ mode, only those locations are listed to which evidences are attributed.

What is more, I wondered if, in _All data_ mode, there is a difference between the locations which would be, analogous to other views, highlighted or grayed-out.

**Comment by mfranke93** [comment]
Rather:
> In *Only active* mode, only those locations are listed to which evidences **that match the current filters** are attributed.

**Comment by mfranke93** [comment]
> What is more, I wondered if, in All data mode, there is a difference between the locations which would be, analogous to other views, highlighted or grayed-out.

We decided against that in [#192@TIK](https://github.tik.uni-stuttgart.de/frankemx/damast/issues/192#issuecomment-3395), but instead apply that behavior to the location confidence filter specifically.

**Comment by mfranke93** [comment]
Exactly.
