### ISSUE TITLE
Match info text and descriptions in "Settings" pane

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#52]
For the different settings and features in the settings pane, descriptions are given not only in the info text, but in the pane itself. In the case of settings, these texts are only displayed when expanding through clicking on the short description.

We need to match these descriptions with the info texts as soon as they are done. Some descriptions in the pane itself could be shortened maybe?

**Comment by mfranke93** [comment]
The idea was that to provide some info directly where the controls are. In contrast to the other views, there is no visualization here to clarify what the controls do, and also there is not as much of a space restriction. I think it is important to have the info here without having to open the info box. I also don't think they are too long, especially with the collapsing text, so I would like to avoid shortening them down. Of course, the descriptions should match the info text (does not have to be the same text, but shouldn't contradict).

**Comment by tutebatti** [comment]
I agree, they might not need to be shortened.
