### ISSUE TITLE
Include section "How to Cite" in Report

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#56]
- Where would I suggest what the section needs to look like? This is not as easy compared to changing the html of the info texts, is it?
- What is more, I am not sure who the "authors" of a report are when it comes to citation. Probably, instead of some standard bibliographical data, it should be something like:

> We suggest to cite this report in the following way: "Report ###UUID### created by ###YOUR NAME### based on the visualization and data of Weltecke, Dorothea et al. "Dhimmis and Muslims. A Tool [...]" accessible via ###URI###."

**Comment by mfranke93** [comment]
> Where would I suggest what the section needs to look like? This is not as easy compared to changing the html of the info texts, is it?

If you don't find an easy way to tweak code/HTML/TeX in a branch, there is no problem with giving me suggestions in the form of copyable text in an issue :)

> What is more, I am not sure who the "authors" of a report are when it comes to citation. Probably, instead of some standard bibliographical data, it should be something like:
> >    We suggest to cite this report in the following way: "Report ###UUID### created by ###YOUR NAME### based on the visualization and data of Weltecke, Dorothea et al. "Dhimmis and Muslims. A Tool [...]" accessible via ###URI###."

I see two issues here:

 1. Visitors without login have no `###YOUR NAME###`
 2. What do you mean with `###URI###`? Do you mean "URL" (to the visualization at HU)?

**Comment by tutebatti** [comment]
I think it will be easier for me to have you change the code in this case.

I just realized that my notation of ###YOUR NAME### is the same as in the dynamically created fields of the rest. However, I meant that the user puts in their own name manually.

With ###URI### I meant the permanent link leading to the report.

**Comment by mfranke93** [comment]
> I just realized that my notation of ###YOUR NAME### is the same as in the dynamically created fields of the rest. However, I meant that the user puts in their own name manually.

I see.

> With ###URI### I meant the permanent link leading to the report.

Okay. That would be a URL then (but technically a URI as well).

> But just in case, could you point out the file(s) (including path) that generate the html and TeX of a report?

Generally everything [here](https://github.com/UniStuttgart-VISUS/damast/tree/main/dhimmis/reporting) in the reporting blueprint directory, but especially the [templates themselves](https://github.com/UniStuttgart-VISUS/damast/tree/main/dhimmis/reporting/templates/reporting). The report sections are split up into the `fragments/`. The `tex/` directory contains the templates for the LaTeX code. It is the same content, but needs different markup code (e.g., `\emph{...}` instead of `<em>...</em>`) and different escape characters for Jinja2.

**Comment by mfranke93** [comment]
I am unsure, with the Google Doc still being in edit: Is this "safe" to work on? I.e., is the formulation final?

**Comment by tutebatti** [comment]
For the _Report_, it should principally be safe to work on. A minor adaption could be due later to put "DAMAST" (occurs twice) in title case.

**Comment by mfranke93** [comment]
There are a lot of inconsistencies and missing information both in the citation text listed here and in #2, and in the Google Doc. Further, the discussions and questions regarding the text are split up between the three places. In my opinion, it is not fruitful to continue discussing this on hypothetical placeholder texts, which also might not address all edge cases and technical details. So:

I have implemented a first version of this and #2 in the scope of PR #59, and have deployed that to the testing server. I would ask you to take a look at how the place URI page and reports look there, and we can discuss feedback and required changes on the "real product" in future :wink: I will send you the credentials for the testing server shortly.

**Comment by tutebatti** [comment]
Thank you. This is probably best.

**Comment by tutebatti** [comment]
I cannot create a report on the test server, it seems.

![grafik](https://user-images.githubusercontent.com/7239968/152356159-ca097402-e2e3-4d3f-ab1c-db5e3242a8e4.png)

**Comment by mfranke93** [comment]
Thanks, you pointed out a small issue with my deployment process :smile: it should work now.

**Comment by tutebatti** [comment]
It does. This should not be part of the citation [anymore, cf. current google doc], however:

> created by [your name here];

**Comment by mfranke93** [comment]
Good to know. That was one of the inconsistencies I was unsure about :+1:

**Comment by tutebatti** [comment]
I also realized that the layout of place URI pages is wider than the one of reports. Is there a reason for this? Not that it really needs to be consistent, but the how-to-cite reference looks much different, that's why I realized the difference.

**Comment by mfranke93** [comment]
> I also realized that the layout of place URI pages is wider than the one of reports. Is there a reason for this? Not that it really needs to be consistent, but the how-to-cite reference looks much different, that's why I realized the difference.

No real reason: Different stylesheets, and different time periods during which they were created. I can probably get this consistent quite easily.

**Comment by tutebatti** [comment]
> I can probably get this consistent quite easily.

If it's not a big deal, I would like that. Should I file a separate issue?

**Comment by mfranke93** [comment]
please do :)

**Comment by tutebatti** [comment]
Also, this:
> Accessed February 3, 2022.
Should be:
> Created February 3, 2022.

**Comment by mfranke93** [comment]
For the report, that makes sense anyways, yeah. For the place URI page (#2), it stays as it is, I suppose.

**Comment by tutebatti** [comment]
> For the place URI page (#2), it stays as it is, I suppose.

Exactly - I hope I'm organized enough by now that I would have posted that in the other issue, if otherwise. ;)
