### ISSUE TITLE
Decision: British or American English for texts in the codebase

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#62]
While work on #6 is ongoing, I keep noticing that @tutebatti is using British English (most noticable: "colour") when he rewrites text sections. I personally have no preference either way, but I think we should all decide on one variant and do that uniformly throughout all texts (not only the info texts).

My two cents: In visualization publications, American English is the norm. That is why the original texts were all spelled in the AE variant. While I am fine with going BE, I would insist on using the spelling "visualization" (as opposed to "visualisation"), as both are acceptable in BE, and using the spelling used in AE as well makes it easier for this project to be found in our domain, and more consistent.

**Comment by tutebatti** [comment]
AE is my preferred choice, too. I wrongly assumed that BE is the common variant for German publications in English for most people. I will gladly correct all texts to be in AE.

**Comment by rpbarczok** [comment]
AE is usually also my preferred choice, but as far as I remember, Dorothea prefers BE, at least in publications. We meet again of Wednesday, so I will out it on our TOP list.
