### ISSUE TITLE
"Evidences without a time attribute are assigned the lowest level of confidence."

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#63]
The sentence above is found in the info text of the view _Confidence_. What is the lowest level, though, `no value`, `false`, or `uncertain`? Intuitively, I would not go for `false`, because only a timespan that is given can be false.

**Comment by mfranke93** [comment]
Ok, so first of (because this sentence is out of context here) this specifically talks about the *time confidence.* And yeah, it is a bit unclear, but should say: "are assigned the *no value* time confidence."

**Comment by tutebatti** [comment]
Alright, thank you.
