### ISSUE TITLE
Place set save button greyed out and no options in place set selection dialog

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#69]
Is it by intention that the button "Save" for saving a place set is disabled in the current running instance?

Also, how will this be handled if visitors are not logged in? Note that I cannot try because of the phenomenon described above.

**Comment by mfranke93** [comment]
Please give more information, and screenshots if possible. There are two save buttons involved in that process, and it works for me.

**Comment by tutebatti** [comment]
The _Save_ button in the modal window is meant. It is greyed out and not clickable:

![grafik](https://user-images.githubusercontent.com/7239968/150807543-ee3b8d24-81db-47f2-aeaa-1ef381eaa2f0.png)

**Comment by mfranke93** [comment]
That should not happen, no. I will have to look into that when I have time.
