### ISSUE TITLE
Behaviour of "Apply" button across all views

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#71]
Is the following true for all views (highlight mine)?

> Note that the selection is not applied until the Apply button is clicked. **This button is disabled if the selected filters are matching the data currently visualized.**

**Comment by mfranke93** [comment]
It should be (i.e., yes, I hope so). The only difference I can think of is the timeline, which does not have an Apply button. The time filter is applied automatically as soon as you release the mouse button.

**Comment by tutebatti** [comment]
Ok, thank you. Just want to make sure its phrased the same way everywhere and the information in bold above is given everywhere. (Everywhere means: where applicable; so not in the timeline, of course.)
