### ISSUE TITLE
Order of "Alternative names" in tooltip of places

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#73]
What is the current order in which the alternative names are listed in the tooltip of places in the location list? It seems to me that it is not systematic (so, probably just in the order entered into the db).

**Comment by mfranke93** [comment]
> It seems to me that it is not systematic (so, probably just in the order entered into the db).

Yes.

**Comment by tutebatti** [comment]
Is it possible to sort it, first, according to language and, second, alphabetically?

On a different note, is it possible to include the transcription in parentheses in the tooltip, similar to the Place URI:

![grafik](https://user-images.githubusercontent.com/7239968/150968430-fb760398-5bdf-48de-bb39-4b8a0d32b292.png)

If so, I will file two separate issues for these two things.

**Comment by mfranke93** [comment]
> Is it possible to sort it, first, according to language and, second, alphabetically?

When you say "by language", I assume you mean alphabetically (Arabic AS > Arabic LS > ... > Greek > Hebrew > ...). Sure, no problem at all.

> On a different note, is it possible to include the transcription in parentheses in the tooltip, similar to the Place URI

Absolutely. The tooltip for the location list predates the transcription field and the reporting functionality, which is why it wasn't there from the start.

> If so, I will file two separate issues for these two things.

Perfect, thanks.

**Comment by tutebatti** [comment]
Great. What is Arabic AS/LS?

Other than that, yes, I meant the first key for ordering to be the language column, and to order alphabetically. (Second key: alternative name, also alphabetically.)

**Comment by mfranke93** [comment]
Arabic Script and Latin Script. I think the Latin Script names were phased out. But the specifics are not important here, just that the results are ordered by language name.
