### ISSUE TITLE
Style guide used for punctuation after italics or bold text

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#76]
Some style guides say to include punctuation in the emphasis if the emphasis ends with the word before it, like

``` html
This is some <em>interesting text.</em>
```

but others don't:

``` html
In <em>this case</em>, the punctuation is outside.
```

I always use the first variant, also consistently in the texts in this repository, but I keep noticing that @tutebatti [changes them back](https://github.com/UniStuttgart-VISUS/damast/commit/893eb573cd8834b93577293c94fbae189d864001#diff-4c0d43645f876f48a23d7d8d1cdbbdaf172b2310d678ddb778fd6ce1932be5dcL14). So I wanted to ask: what style guide do you want to use here and which variant to agree upon?

**Comment by rpbarczok** [comment]
I feel like the second variant is the more common in our trade, without being able to give a normative source.

**Comment by tutebatti** [comment]
As far as I know, in fact, AE uses the former, at least with quotation marks. Personally, I find that totally absurd. But maybe we should stick to the Chicago style (and AE practice), if we use that for citing...

**Comment by mfranke93** [comment]
I am used to the former being used. Honestly, with italics, it only really is noticeable with exclamation and question marks anyways, but to me it looks odd if those don't match:

 - *No.* real *difference*. (`*No.* real *difference*.`)
 - *Some!* difference *here*! (`*Some!* difference *here*!`) Here, the italicized word kind of collides with the straight-up exclamation mark, which to me looks wrong.
 - **Same.** here **with**. these **punctuation?** **marks**! (`**Same.** here **with**. these **punctuation?** **marks**!) The non-bold punctuation directly after bold text just looks wrong to me, like, too skinny.

I guess that's my personal opinion as well, but it is also the way I will write it if I don't think about it. Regarding the Chicago Manual of Style, funny thing: I was curious and researched this, and it seems [[1](https://english.stackexchange.com/questions/9878/should-punctuation-surrounding-italicised-words-be-italicised), [2](http://the-word-blog.com/2009/04/28/formatting-ink-italics-punctuation/)] that the CMS said to do the first variant until the 14th edition, but switched to the second variant for the 15th and 16th. But of course, other styles differ again.

I am open to both (although the second one looks unnatural to me), but we should decide on one.

**Comment by tutebatti** [comment]
Thank you for these examples. This shows the difference to the "problem" with the quotation marks. Within the source code, I didn't see what you get (:wink:) and the examples you brought up make me tend to the former as well.

**Comment by mfranke93** [comment]
Alright. Then I think we are in accord here!

Side note regarding the "seeing what you get": You can always open the HTML files directly in a browser when editing. The styling will not be the exact same, but functionally equivalent. And there will be some Jinja2 stuff still visible, but it shouldn't hurt. Or you can even get the development server started on your end ;) but that's probably overkill.
