### ISSUE TITLE
Bar under lower graph of timeline only shows while changing selection

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#80]
When, first, using the lower graph (_overview_) of the _Timeline_ to "zoom" inside the upper graph (_main timeline_), and then clicking and dragging inside the upper graph to filter, the bar below the lower graph only shows while clicking and dragging. (Note: In the screenshots, the cursor is not represented the way it is displayed while I took them. In the first screenshot, it was an arrow to modify the rectangle, in the second, it was a hand.)

![grafik](https://user-images.githubusercontent.com/7239968/151781931-4e6833bb-82e4-4814-8395-a641d90f5d81.png)

![grafik](https://user-images.githubusercontent.com/7239968/151782138-1601f473-a77e-42d2-b71d-d7fa22828d32.png)

**Comment by mfranke93** [comment]
Yes, I see the issue. It happens without the first step, as well.

I am pretty sure I also already know what is happening. Behind the scenes, there are two steps happening: First, the filter arguments are sent from the UI to a separate process (`WebWorker`) that handles all dataset operations. This is done asynchronously to make the UI more snappy. The new data and the filters are then sent back to the UI in a second step. And it seems that in this second step, the UI does not redraw that bar.

**Comment by mfranke93** [comment]
``` diff
diff --git i/src/vis/timeline.ts w/src/vis/timeline.ts
index a46459a..c5255ed 100644
--- i/src/vis/timeline.ts
+++ w/src/vis/timeline.ts
@@ -181,6 +181,8 @@ export default class Timeline extends View<any, any> {
 
   private timeFilterIndicator(data: [number, number]): void {
     const h0 = this._cached_bbox.height - brush_height;
+    const noFilter = JSON.stringify(this.totalDomain) === JSON.stringify(data);
+
     let r = this.overview_g.selectAll('rect.overview-filter-indicator')
       .data([data]) as d3.Selection<SVGRectElement, any, any, any>;
     r.enter()
@@ -192,7 +194,7 @@ export default class Timeline extends View<any, any> {
       .attr('height', 5)
       .attr('width', d => this.x_overview(d[1]) - this.x_overview(d[0]))
       .attr('fill', 'white')
-      .attr('opacity', 0.6);
+      .attr('opacity', noFilter ? 0 : 0.6);
   }
 
   private _cached_bbox: DOMRect = null;
@@ -284,8 +286,8 @@ export default class Timeline extends View<any, any> {
       this.zoom(scroll);
     });
 
-    this.brushMoved();
     this.createOverview(d2, bbox.width, bbox.height);
+    this.brushMoved();
   }
 
   private brushMoved(): void {
```
