### ISSUE TITLE
Change Sources to Chicago Manual of Style

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#85]
To be consistent throughout the whole system, we should probably change the sources to Chicago Manual of Style. What is the best way to do that, @mfranke93 ?

Note: This only pertains to the Sources, not to the Source Instances - although the column "Page" would need to be corrected, there, too.

**Comment by mfranke93** [comment]
You would need to update the `name` in the `source` table. @rpbarczok did some updates there recently (with the short names) already, so he should know how to do that.

**Comment by tutebatti** [comment]
@rpbarczok If you could send to me bibliographical data of all sources as a file that can be handled by Citavi or Zotero, I could correct the bibliographical data there and produce consistent references in the form of Chicago MS. I would need that for the startpage anyways (cf. #7).

**Comment by rpbarczok** [comment]
Sure. I will deal with that immediately

**Comment by tutebatti** [comment]
After going through the sources, I suggest to use the same abbreviations throughout, also on the start page (cf. #7), similar to the Prolegomena. This might affect the shortnames for external references (cf. #86) as well.

**Comment by tutebatti** [comment]
@rpbarczok As far as I understand, shorttitles and long citation are fixed now. Will you update that in the database?

**Comment by tutebatti** [comment]
This is resolved, right @rpbarczok ?
