### ISSUE TITLE
Change explanations in list "See also" in Place URI page

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#86]
Are the explanations following the URLs consistent throughout and stored at some central place, @mfranke93 ?
E.g., I would change

> The Encyclopaedia of Islam First Edition Online

to something like

> The Encyclopaedia of Islam, First Edition (Online).

**Comment by mfranke93** [comment]
See (or edit) column `name` in table `external_database`.

**Comment by tutebatti** [comment]
Since I have not edited the database directly yet, what is the backup policy? Can I break something just editing the entries of that column (or the one mentioned in #85)?

**Comment by mfranke93** [comment]
I don't think you can "break" much (database and code-wise) editing the name column, or any other of the text columns. I would suggest keeping the hands off any columns that contain foreign keys (IDs from other tables). You *can* of course "break" stuff data-wise; i.e., the end result is different not only in spelling, but semantically, but that's under your control.

The database is backed up daily. The edits necessary here are less invasive than what is done daily via the GeoDB-Editor, and I think that in the last two years, we have not had to restore a backup yet.

Still, if you are more comfortable with that option, you can do the edit in a CSV file or Excel sheet instead and let me put it back into the database. In that case, the file would need a column with the ID in it so it can be matched.

**Comment by tutebatti** [comment]
Thank you for the information. In fact, I would prefer the csv option. Maybe we can arrange a short video call session, where you show me how to best export a csv from a table. (I might need that later anyways to process the data without Damast.)

**Comment by mfranke93** [comment]
> (or the one mentioned in https://github.com/UniStuttgart-VISUS/damast/issues/85)

We (me and @rpbarczok) had some issues (#3, mainly [from here](https://github.com/UniStuttgart-VISUS/damast/issues/3#issuecomment-1015584519)) before because for the data export to DaRUS and the public version, we use the *short name* of the source to remove sources that shouldn't be in that. For that, the short name in the export script and the database need to match automatically, of course. But this only pertains to the `source.short` and `tag.tagname` fields, IIRC.

> Maybe we can arrange a short video call session, where you show me how to best export a csv from a table.

Sure. Just let me know when you are free today.

**Comment by tutebatti** [comment]
I have changed that directly via pgAdmin. @rpbarczok, are the abbreviations used there the same as in the commentary regarding places? I changed two, one to e-GEDSH, one to EIr.

**Comment by rpbarczok** [comment]
Yes, at least they should be. I am looking through the comments of every place instance at the moment but I am not finished yet. We should also, as discussed recently personally, discuss the shortnames in the DB. When we change them, we have to inform Max and look through the comments column of the place table again. But I do not use the short forms very often.

**Comment by tutebatti** [comment]
If I understood correctly from our discussion yesterday, some of the monographs will also be shortened, e.g. to `Timm`.

**Comment by rpbarczok** [comment]
Yes, I shortened all title that are used as sources of evidences. If you like we can meet and discuss them.

**Comment by tutebatti** [comment]
This issue can be closed, right, @rpbarczok ?
