### ISSUE TITLE
Query Description in Report for visitors

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#87]
What text is displayed instead of ###username### for visitors here?

> This report was generated using Damast on Tuesday, January 18, 2022, at 11:25 CET by ###username### via direct export from the visualization.

**Comment by mfranke93** [comment]
"visitor"

![image](https://user-images.githubusercontent.com/9373678/152187180-5fff8f72-d9d3-444c-9e0f-1197adaa78f0.png)

**Comment by mfranke93** [comment]
In general, visitors are "logged in" under the `visitor` user, which has some special handling. See #28

**Comment by tutebatti** [comment]
Thank you!
