### ISSUE TITLE
Adapt place URI pages and reports to have same/similar layout, e.g. width.

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#90]
Cf. https://github.com/UniStuttgart-VISUS/damast/issues/56#issuecomment-1029053427

**Comment by mfranke93** [comment]
In your opinion, which of the two looks nicer: the placed URI page or the HTML report?

**Comment by mfranke93** [comment]
I have made first adaptations and also deployed that to the testing server for your reference. See some screenshots below as well. However, I found one reason why the report will always be a bit more narrow: I added a left margin to everything there, where the reference numbers (like "[P204]" for a place) are placed. 

### Place URI Page
![image](https://user-images.githubusercontent.com/9373678/152383693-24eec061-8431-4b27-ba0b-9c90c6555482.png)


### Report, 1
![image](https://user-images.githubusercontent.com/9373678/152383608-3ad81137-1153-47e5-8ee3-645ef5ddf055.png)

###Report, 2
![image](https://user-images.githubusercontent.com/9373678/152383506-c6ea09dd-5078-4d3c-bee6-f7305443e17c.png)

**Comment by tutebatti** [comment]
Indentation looks fine to me, but the overall width is greater now, right? I would leave it at that.

**Comment by mfranke93** [comment]
Will be merged into `main` with `v1.0.5`, but no more space in the PR for linked issues, so I am closing this here.
