### ISSUE TITLE
Consider the Arabic ʿain letter for sorting place names

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#94]
@tutebatti 's comment [here](https://github.com/UniStuttgart-VISUS/damast/blob/6f2b711a9270be351a56af8e92d431b6ccbd4ef0/dhimmis/vis/templates/vis/info/location-list.html#L58) regarding the Arabic letter *'ain* made me realize we are not 100% on the same page regarding that. At the moment, this is *not* ignored for sorting, only the "normal" ASCII apostrophe (`U+0027` APOSTROPHE) and  `U+2019` RIGHT SINGLE QUOTATION MARK (&#x2019;) are (see [here](https://github.com/UniStuttgart-VISUS/damast/blob/49d7735215727a934bf94bdea5edcc12f5c1dd72/src/common/ignore-name-prefixes.ts#L8) and [here](https://github.com/UniStuttgart-VISUS/damast/blob/49d7735215727a934bf94bdea5edcc12f5c1dd72/dhimmis/reporting/place_sort.py#L5)).

As far as I know, the 'ain is not used in the *primary* place names (we discussed this some months or years ago), which is why we only use those characters. If you want, I could add the U+02BB ʻ MODIFIER LETTER TURNED COMMA and U+02BF ʿ MODIFIER LETTER LEFT HALF RING (both used for 'ain) characters as well. Let me know.

**Comment by tutebatti** [comment]
At best, in the data itself, there should be only __one__ Unicode sign for the simplified form (U+0027) and __one__ for the "scientific" transcription (U+02BF ʿ MODIFIER LETTER LEFT HALF RING). If this is consistent in the data, we can decide on the sorting.

Then, I would tend to treat both signs the same, namely neglect them when sorting, because we use the "Latin" sorting logic for the transcriptions now.

At any rate, I need to double-check this with the others.

**Comment by tutebatti** [comment]
Apart from the consistency of the data, which we will take care of in the coming days, we decided to exclude the following signs from sorting, which generally follows the Latin order.
 
- U+0027 APOSTROPHE [used in simple transcription for both _ʿain_ and _hamza_]
- U+02BF ʿ MODIFIER LETTER LEFT HALF RING [used in scientific transcription for _ʿain_]
- U+02BE ʾ MODIFIER LETTER RIGHT HALF RING [used in scientific transcription for _hamza_]

This might affect the Armenian scientific transcription as well, which uses U+02BF as well, but that should not cause any problems.

@rpbarczok, please confirm.

**Comment by rpbarczok** [comment]
confirmed
