### ISSUE TITLE
How to handle the grouping of Samaritans in the religion hierarchy

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#96]
As per our email thread, I outlined two possibilities:

1. Move the Samaritans to the top level of the hierarchy. Deal with the five-circle issue in the map symbols according to your preferences, and use a symbol and color of your choosing for the Samaritans.
2. Introduce a common parent for Judaism and Samaritans in the data. Use a name, abbreviation, symbol, and color of your choosing for that parent group.

In both cases, please let me know the specifics.

**Comment by rpbarczok** [comment]
Since we have now your input, we can discuss the matter tomorrow and we will come back to you.

**Comment by tutebatti** [comment]
As far as I understood, we will leave it as is and explain our reasoning on the startpage and the publication. Right, @rpbarczok? (If so, you can close this issue.)

**Comment by rpbarczok** [comment]
Yes. No changes.
